spring:
  application.name: restapi
  datasource:
    url: jdbc:h2:mem:restapi
    username: user
    password: pass
    generate-unique-name: false
    name: "restapi"
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #Grazie alla configurazione sottostante le @Entity vengono salvate su DB in minuscolo.
        #Per referenziare nelle query bisogna usare le virgolette (es. SELECT * FROM "subscription")
        #altrimenti vengono parsate automaticamente in maiuscolo (USER, SUBSCRIPTION)
        globally_quoted_identifiers: true
  sql.init.mode: always

logging:
  level:
    org.springframework.web: DEBUG
    com.crustwerk.restapi: DEBUG
    root: INFO